version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Navigating to the backend directory..."
      - cd backend
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Packaging the application..."
      - zip -r lambda-package.zip ./ -x buildspec.yml -x .git/** -x node_modules/** -x lambda-package.zip -x *.log
      - echo "Build completed"

  post_build:
    commands:
      - echo "Updating Lambda function code..."
      - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://lambda-package.zip
      - sleep 10
      - echo "Updating Lambda function configuration..."
      - aws lambda update-function-configuration --function-name $LAMBDA_FUNCTION_NAME --handler app.handler

artifacts:
  files:
    - lambda-package.zip

